# Generated by Django 6.0.3 on 2026-04-20 07:27

import charles.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charles', '0002_loginattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.FileField(blank=True, help_text='PNG, JPEG, GIF, or WEBP only. Maximum size: 2 MB.', upload_to=charles.uploads.avatar_upload_to, validators=[charles.uploads.validate_avatar_upload]),
        ),
        migrations.AddField(
            model_name='profile',
            name='document',
            field=models.FileField(blank=True, help_text='PDF only. Maximum size: 5 MB.', upload_to=charles.uploads.document_upload_to, validators=[charles.uploads.validate_document_upload]),
        ),
    ]
