# Generated by Django 5.2.13 on 2026-04-20 08:40

import portfolio.uploads
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(max_length=2000)),
                ('avatar', models.FileField(blank=True, help_text='PNG, JPEG, GIF, or WEBP only. Maximum size: 2 MB.', upload_to=portfolio.uploads.avatar_upload_to, validators=[portfolio.uploads.validate_avatar_upload])),
                ('document', models.FileField(blank=True, help_text='PDF only. Maximum size: 5 MB.', upload_to=portfolio.uploads.document_upload_to, validators=[portfolio.uploads.validate_document_upload])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Submission',
                'verbose_name_plural': 'Submissions',
                'ordering': ('-created_at',),
            },
        ),
    ]
